Trace
---------------------------------------------------------------
    Defining frame__adventure_works__product_list_price_histories
---------------------------------------------------------------
;
Trace Setting variables...;
Let val__source_path = 'lib://DataFiles/Analytical Data Storage System/QVD/$(val__environment)/data_according_to_system/raw__adventure_works__product_list_price_histories.qvd';
Let val__target_path = '$(val__qvd_path__dab)/frame__adventure_works__product_list_price_histories.qvd';
Let val__source_create_time = Timestamp(FileTime('$(val__source_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__target_create_time = Timestamp(FileTime('$(val__target_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__source_is_newer = If('$(val__source_create_time)' > '$(val__target_create_time)', 1, 0);

Set var__hook__product = 'product__adventure_works|' & Text([product_id]);
Set var__hook__epoch__start_date = 'epoch__date|' & Text([start_date]);
Set var__hook__product_list_price_history = $(var__hook__product) & '~' & $(var__hook__epoch__start_date);
Set var__record_version = Window(RecNo(), [product_id], 'Asc', [record_loaded_at]);

Set var__valid_from = If(
        $(var__record_version) = 1,
        Timestamp#('1970-01-01 00:00:00.000', 'YYYY-MM-DD hh:mm:ss.fff'),
        [record_loaded_at]
    )
;

Set var__valid_to = Coalesce(
        Window([record_loaded_at], [product_id], 'Asc', [record_loaded_at], 1, 1, 1),
        Timestamp#('9999-12-31 23:59:59.999', 'YYYY-MM-DD hh:mm:ss.fff')
    )
;

Set var__is_current_record = If(
        $(var__valid_to) = Timestamp#('9999-12-31 23:59:59.999', 'YYYY-MM-DD hh:mm:ss.fff'),
        1,
        0
    )
;

Set var__record_updated_at = If(
        $(var__is_current_record),
        [record_loaded_at],
        $(var__valid_to)
    )
;

Set var__pit_hook__product_list_price_history = $(var__hook__product_list_price_history) & '~epoch__valid_from|' & Text($(var__valid_from));

If $(val__source_is_newer) = 1 Then 

    Trace Source is newer, loading & transforming data...;
    [frame__adventure_works__product_list_price_histories]:
    Load
        Text($(var__pit_hook__product_list_price_history)) As [_pit_hook__product_list_price_history],
        Text($(var__hook__product_list_price_history)) As [_hook__product_list_price_history],
        Text($(var__hook__product)) As [_hook__product],
        Text($(var__hook__epoch__start_date)) As [_hook__epoch__start_date],
        Num#([product_id]) As [product_list_price_history__product_id],
        Text([start_date]) As [product_list_price_history__start_date],
        Date(Num#([end_date]), 'YYYY-MM-DD') As [product_list_price_history__end_date],
        Num#([list_price]) As [product_list_price_history__list_price],
        Date(Num#([modified_date]), 'YYYY-MM-DD') As [product_list_price_history__modified_date],
        Text([record_hash]) As [product_list_price_history__record_hash],
        Timestamp([record_loaded_at], 'YYYY-MM-DD hh:mm:ss.fff') As [product_list_price_history__record_loaded_at],
        Timestamp($(var__record_updated_at), 'YYYY-MM-DD hh:mm:ss.fff') As [product_list_price_history__record_updated_at],
        Num($(var__record_version)) As [product_list_price_history__record_version],
        Timestamp($(var__valid_from), 'YYYY-MM-DD hh:mm:ss.fff') As [product_list_price_history__record_valid_from],
        Timestamp($(var__valid_to), 'YYYY-MM-DD hh:mm:ss.fff') As [product_list_price_history__record_valid_to],
        Num($(var__is_current_record)) As [product_list_price_history__is_current_record]

    From
        [lib://DataFiles/Analytical Data Storage System/QVD/$(val__environment)/data_according_to_system/raw__adventure_works__product_list_price_histories.qvd] (qvd)
    ;

    Trace Commenting table...;
    Comment Table [frame__adventure_works__product_list_price_histories] With 'Changes in the list price of a product over time.';

    Trace Commenting fields...;
    Comment Field [_pit_hook__product_list_price_history] With 'Point in time version of _hook__product_list_price_history.';
    Comment Field [_hook__product_list_price_history] With 'Composite hook using _hook__product and _hook__epoch__start_date.';
    Comment Field [_hook__product] With 'Hook for product_id using keyset: product__adventure_works.';
    Comment Field [_hook__epoch__start_date] With 'Hook for start_date using keyset: epoch__date.';
    Comment Field [product_list_price_history__product_id] With 'Product identification number. Foreign key to Product.ProductID.';
    Comment Field [product_list_price_history__start_date] With 'List price start date.';
    Comment Field [product_list_price_history__end_date] With 'List price end date.';
    Comment Field [product_list_price_history__list_price] With 'Product list price.';
    Comment Field [product_list_price_history__modified_date] With 'Date and time the record was last updated.';
    Comment Field [product_list_price_history__record_hash] With 'Hash of the record.';
    Comment Field [product_list_price_history__record_loaded_at] With 'Date and time the record was loaded.';
    Comment Field [product_list_price_history__record_updated_at] With 'Date and time the record was last updated.';
    Comment Field [product_list_price_history__record_version] With 'Version of the record.';
    Comment Field [product_list_price_history__record_valid_from] With 'Date and time the record was valid from.';
    Comment Field [product_list_price_history__record_valid_to] With 'Date and time the record was valid to.';
    Comment Field [product_list_price_history__is_current_record] With '1 if the record is current, 0 otherwise.';

    Trace Storing data...;
    Store [frame__adventure_works__product_list_price_histories] Into [$(val__qvd_path__dab)/frame__adventure_works__product_list_price_histories.qvd] (qvd);

    Trace Dropping table...;
    Drop Table [frame__adventure_works__product_list_price_histories];

Else
    Trace Source is older than target, skipping...;

End If

Trace Resetting variables...;
Let val__source_path = Null();
Let val__target_path = Null();
Let val__source_create_time = Null();
Let val__target_create_time = Null();
Let val__source_is_newer = Null();

Let var__record_version = Null();
Let var__valid_from = Null();
Let var__valid_to = Null();
Let var__is_current_record = Null();
Let var__record_updated_at = Null();
Let var__hook__product_list_price_history = Null();
Let var__hook__product = Null();
Let var__hook__epoch__start_date = Null();
Let var__pit_hook__product_list_price_history = Null();
