Trace
---------------------------------------------------------------
    Defining frame__adventure_works__transaction_history_archives
---------------------------------------------------------------
;
Trace Setting variables...;
Let val__source_path = 'lib://DataFiles/Analytical Data Storage System/QVD/$(val__environment)/data_according_to_system/raw__adventure_works__transaction_history_archives.qvd';
Let val__target_path = '$(val__qvd_path__dab)/frame__adventure_works__transaction_history_archives.qvd';
Let val__source_create_time = Timestamp(FileTime('$(val__source_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__target_create_time = Timestamp(FileTime('$(val__target_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__source_is_newer = If('$(val__source_create_time)' > '$(val__target_create_time)', 1, 0);

Set var__hook__transaction_history_archive = 'product__adventure_works|' & Text([transaction_id]);
Set var__hook__product = 'product__adventure_works|' & Text([product_id]);
Set var__hook__order__reference = 'order__adventure_works|' & Text([reference_order_id]);
Set var__record_version = Window(RecNo(), [transaction_id], 'Asc', [record_loaded_at]);

Set var__valid_from = If(
        $(var__record_version) = 1,
        Timestamp#('1970-01-01 00:00:00.000', 'YYYY-MM-DD hh:mm:ss.fff'),
        [record_loaded_at]
    )
;

Set var__valid_to = Coalesce(
        Window([record_loaded_at], [transaction_id], 'Asc', [record_loaded_at], 1, 1, 1),
        Timestamp#('9999-12-31 23:59:59.999', 'YYYY-MM-DD hh:mm:ss.fff')
    )
;

Set var__is_current_record = If(
        $(var__valid_to) = Timestamp#('9999-12-31 23:59:59.999', 'YYYY-MM-DD hh:mm:ss.fff'),
        1,
        0
    )
;

Set var__record_updated_at = If(
        $(var__is_current_record),
        [record_loaded_at],
        $(var__valid_to)
    )
;

Set var__pit_hook__transaction_history_archive = $(var__hook__transaction_history_archive) & '~epoch__valid_from|' & Text($(var__valid_from));

If $(val__source_is_newer) = 1 Then 

    Trace Source is newer, loading & transforming data...;
    [frame__adventure_works__transaction_history_archives]:
    Load
        Text($(var__pit_hook__transaction_history_archive)) As [_pit_hook__transaction_history_archive],
        Text($(var__hook__transaction_history_archive)) As [_hook__transaction_history_archive],
        Text($(var__hook__product)) As [_hook__product],
        Text($(var__hook__order__reference)) As [_hook__order__reference],
        Num#([transaction_id]) As [transaction_history_archive__transaction_id],
        Num#([product_id]) As [transaction_history_archive__product_id],
        Num#([reference_order_id]) As [transaction_history_archive__reference_order_id],
        Num#([reference_order_line_id]) As [transaction_history_archive__reference_order_line_id],
        Date(Num#([transaction_date]), 'YYYY-MM-DD') As [transaction_history_archive__transaction_date],
        Text([transaction_type]) As [transaction_history_archive__transaction_type],
        Num#([quantity]) As [transaction_history_archive__quantity],
        Num#([actual_cost]) As [transaction_history_archive__actual_cost],
        Date(Num#([modified_date]), 'YYYY-MM-DD') As [transaction_history_archive__modified_date],
        Text([record_hash]) As [transaction_history_archive__record_hash],
        Timestamp([record_loaded_at], 'YYYY-MM-DD hh:mm:ss.fff') As [transaction_history_archive__record_loaded_at],
        Timestamp($(var__record_updated_at), 'YYYY-MM-DD hh:mm:ss.fff') As [transaction_history_archive__record_updated_at],
        Num($(var__record_version)) As [transaction_history_archive__record_version],
        Timestamp($(var__valid_from), 'YYYY-MM-DD hh:mm:ss.fff') As [transaction_history_archive__record_valid_from],
        Timestamp($(var__valid_to), 'YYYY-MM-DD hh:mm:ss.fff') As [transaction_history_archive__record_valid_to],
        Num($(var__is_current_record)) As [transaction_history_archive__is_current_record]

    From
        [lib://DataFiles/Analytical Data Storage System/QVD/$(val__environment)/data_according_to_system/raw__adventure_works__transaction_history_archives.qvd] (qvd)
    ;

    Trace Commenting table...;
    Comment Table [frame__adventure_works__transaction_history_archives] With 'Transactions for previous years.';

    Trace Commenting fields...;
    Comment Field [_pit_hook__transaction_history_archive] With 'Point in time version of _hook__transaction_history_archive.';
    Comment Field [_hook__transaction_history_archive] With 'Hook for transaction_id using keyset: product__adventure_works.';
    Comment Field [_hook__product] With 'Hook for product_id using keyset: product__adventure_works.';
    Comment Field [_hook__order__reference] With 'Hook for reference_order_id using keyset: order__adventure_works.';
    Comment Field [transaction_history_archive__transaction_id] With 'Primary key for TransactionHistoryArchive records.';
    Comment Field [transaction_history_archive__product_id] With 'Product identification number. Foreign key to Product.ProductID.';
    Comment Field [transaction_history_archive__reference_order_id] With 'Purchase order, sales order, or work order identification number.';
    Comment Field [transaction_history_archive__reference_order_line_id] With 'Line number associated with the purchase order, sales order, or work order.';
    Comment Field [transaction_history_archive__transaction_date] With 'Date and time of the transaction.';
    Comment Field [transaction_history_archive__transaction_type] With 'W = Work Order, S = Sales Order, P = Purchase Order.';
    Comment Field [transaction_history_archive__quantity] With 'Product quantity.';
    Comment Field [transaction_history_archive__actual_cost] With 'Product cost.';
    Comment Field [transaction_history_archive__modified_date] With 'Date and time the record was last updated.';
    Comment Field [transaction_history_archive__record_hash] With 'Hash of the record.';
    Comment Field [transaction_history_archive__record_loaded_at] With 'Date and time the record was loaded.';
    Comment Field [transaction_history_archive__record_updated_at] With 'Date and time the record was last updated.';
    Comment Field [transaction_history_archive__record_version] With 'Version of the record.';
    Comment Field [transaction_history_archive__record_valid_from] With 'Date and time the record was valid from.';
    Comment Field [transaction_history_archive__record_valid_to] With 'Date and time the record was valid to.';
    Comment Field [transaction_history_archive__is_current_record] With '1 if the record is current, 0 otherwise.';

    Trace Storing data...;
    Store [frame__adventure_works__transaction_history_archives] Into [$(val__qvd_path__dab)/frame__adventure_works__transaction_history_archives.qvd] (qvd);

    Trace Dropping table...;
    Drop Table [frame__adventure_works__transaction_history_archives];

Else
    Trace Source is older than target, skipping...;

End If

Trace Resetting variables...;
Let val__source_path = Null();
Let val__target_path = Null();
Let val__source_create_time = Null();
Let val__target_create_time = Null();
Let val__source_is_newer = Null();

Let var__record_version = Null();
Let var__valid_from = Null();
Let var__valid_to = Null();
Let var__is_current_record = Null();
Let var__record_updated_at = Null();
Let var__hook__transaction_history_archive = Null();
Let var__hook__product = Null();
Let var__hook__order__reference = Null();
Let var__pit_hook__transaction_history_archive = Null();
