Trace
---------------------------------------------------------------
    Defining peripheral__adventure_works__sales_person_quota_histories
---------------------------------------------------------------
;
Trace Setting variables...;
Let val__source_path = '$(val__qvd_path__dab)/frame__adventure_works__sales_person_quota_histories.qvd';
Let val__target_path = '$(val__qvd_path__dar)/peripheral__adventure_works__sales_person_quota_histories.qvd';
Let val__source_create_time = Timestamp(FileTime('$(val__source_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__target_create_time = Timestamp(FileTime('$(val__target_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__source_is_newer = If('$(val__source_create_time)' > '$(val__target_create_time)', 1, 0);

Trace Checking if source is newer...;

If $(val__source_is_newer) = 1 Then 

    Trace Source is newer, loading & transforming data...;
    [peripheral__adventure_works__sales_person_quota_histories]:
    Load
        [_pit_hook__person__sales],
        [sales_person_quota_history__business_entity_id],
        [sales_person_quota_history__quota_date],
        [sales_person_quota_history__sales_quota],
        [sales_person_quota_history__rowguid],
        [sales_person_quota_history__modified_date],
        [sales_person_quota_history__record_hash],
        [sales_person_quota_history__record_loaded_at],
        [sales_person_quota_history__record_updated_at],
        [sales_person_quota_history__record_version],
        [sales_person_quota_history__record_valid_from],
        [sales_person_quota_history__record_valid_to],
        [sales_person_quota_history__is_current_record]

    From
        [$(val__source_path)] (qvd)
    ;

    Trace Commenting table...;
    Comment Table [peripheral__adventure_works__sales_person_quota_histories] With 'Sales performance tracking.';

    Trace Commenting fields...;
    Comment Field [_pit_hook__person__sales] With 'Point in time hook for business_entity_id using keyset: person__sales__adventure_works.';
    Comment Field [sales_person_quota_history__business_entity_id] With 'Sales person identification number. Foreign key to SalesPerson.BusinessEntityID.';
    Comment Field [sales_person_quota_history__quota_date] With 'Sales quota date.';
    Comment Field [sales_person_quota_history__sales_quota] With 'Sales quota amount.';
    Comment Field [sales_person_quota_history__rowguid] With 'ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.';
    Comment Field [sales_person_quota_history__modified_date] With 'Date and time the record was last updated.';
    Comment Field [sales_person_quota_history__record_hash] With 'Hash of the record.';
    Comment Field [sales_person_quota_history__record_loaded_at] With 'Date and time the record was loaded.';
    Comment Field [sales_person_quota_history__record_updated_at] With 'Date and time the record was last updated.';
    Comment Field [sales_person_quota_history__record_version] With 'Version of the record.';
    Comment Field [sales_person_quota_history__record_valid_from] With 'Date and time the record was valid from.';
    Comment Field [sales_person_quota_history__record_valid_to] With 'Date and time the record was valid to.';
    Comment Field [sales_person_quota_history__is_current_record] With '1 if the record is current, 0 otherwise.';

    Trace Storing data...;
    Store [peripheral__adventure_works__sales_person_quota_histories] Into [$(val__target_path)] (qvd);

    Trace Dropping table...;
    Drop Table [peripheral__adventure_works__sales_person_quota_histories];

Else
    Trace Source is older than target, skipping...;

End If

Trace Resetting variables...;
Let val__source_path = Null();
Let val__target_path = Null();
Let val__source_create_time = Null();
Let val__target_create_time = Null();
Let val__source_is_newer = Null();
