Trace
---------------------------------------------------------------
    Defining peripheral__adventure_works__product_model_illustrations
---------------------------------------------------------------
;
Trace Setting variables...;
Let val__source_path = '$(val__qvd_path__dab)/frame__adventure_works__product_model_illustrations.qvd';
Let val__target_path = '$(val__qvd_path__dar)/peripheral__adventure_works__product_model_illustrations.qvd';
Let val__source_create_time = Timestamp(FileTime('$(val__source_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__target_create_time = Timestamp(FileTime('$(val__target_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__source_is_newer = If('$(val__source_create_time)' > '$(val__target_create_time)', 1, 0);

Trace Checking if source is newer...;

If $(val__source_is_newer) = 1 Then 

    Trace Source is newer, loading & transforming data...;
    [peripheral__adventure_works__product_model_illustrations]:
    Load
        [_pit_hook__product_model_illustration],
        [product_model_illustration__product_model_id],
        [product_model_illustration__illustration_id],
        [product_model_illustration__modified_date],
        [product_model_illustration__record_hash],
        [product_model_illustration__record_loaded_at],
        [product_model_illustration__record_updated_at],
        [product_model_illustration__record_version],
        [product_model_illustration__record_valid_from],
        [product_model_illustration__record_valid_to],
        [product_model_illustration__is_current_record]

    From
        [$(val__source_path)] (qvd)
    ;

    Trace Commenting table...;
    Comment Table [peripheral__adventure_works__product_model_illustrations] With 'Cross-reference table mapping product models and illustrations.';

    Trace Commenting fields...;
    Comment Field [_pit_hook__product_model_illustration] With 'Point in time version of _hook__product_model_illustration.';
    Comment Field [product_model_illustration__product_model_id] With 'Primary key. Foreign key to ProductModel.ProductModelID.';
    Comment Field [product_model_illustration__illustration_id] With 'Primary key. Foreign key to Illustration.IllustrationID.';
    Comment Field [product_model_illustration__modified_date] With 'Date and time the record was last updated.';
    Comment Field [product_model_illustration__record_hash] With 'Hash of the record.';
    Comment Field [product_model_illustration__record_loaded_at] With 'Date and time the record was loaded.';
    Comment Field [product_model_illustration__record_updated_at] With 'Date and time the record was last updated.';
    Comment Field [product_model_illustration__record_version] With 'Version of the record.';
    Comment Field [product_model_illustration__record_valid_from] With 'Date and time the record was valid from.';
    Comment Field [product_model_illustration__record_valid_to] With 'Date and time the record was valid to.';
    Comment Field [product_model_illustration__is_current_record] With '1 if the record is current, 0 otherwise.';

    Trace Storing data...;
    Store [peripheral__adventure_works__product_model_illustrations] Into [$(val__target_path)] (qvd);

    Trace Dropping table...;
    Drop Table [peripheral__adventure_works__product_model_illustrations];

Else
    Trace Source is older than target, skipping...;

End If

Trace Resetting variables...;
Let val__source_path = Null();
Let val__target_path = Null();
Let val__source_create_time = Null();
Let val__target_create_time = Null();
Let val__source_is_newer = Null();
