Trace
---------------------------------------------------------------
    Defining peripheral__adventure_works__work_order_routings
---------------------------------------------------------------
;
Trace Setting variables...;
Let val__source_path = '$(val__qvd_path__dab)/frame__adventure_works__work_order_routings.qvd';
Let val__target_path = '$(val__qvd_path__dar)/peripheral__adventure_works__work_order_routings.qvd';
Let val__source_create_time = Timestamp(FileTime('$(val__source_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__target_create_time = Timestamp(FileTime('$(val__target_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__source_is_newer = If('$(val__source_create_time)' > '$(val__target_create_time)', 1, 0);

Trace Checking if source is newer...;

If $(val__source_is_newer) = 1 Then 

    Trace Source is newer, loading & transforming data...;
    [peripheral__adventure_works__work_order_routings]:
    Load
        [_pit_hook__work_order_routing],
        [work_order_routing__work_order_id],
        [work_order_routing__product_id],
        [work_order_routing__operation_sequence],
        [work_order_routing__location_id],
        [work_order_routing__scheduled_start_date],
        [work_order_routing__scheduled_end_date],
        [work_order_routing__actual_start_date],
        [work_order_routing__actual_end_date],
        [work_order_routing__actual_resource_hrs],
        [work_order_routing__planned_cost],
        [work_order_routing__actual_cost],
        [work_order_routing__modified_date],
        [work_order_routing__record_hash],
        [work_order_routing__record_loaded_at],
        [work_order_routing__record_updated_at],
        [work_order_routing__record_version],
        [work_order_routing__record_valid_from],
        [work_order_routing__record_valid_to],
        [work_order_routing__is_current_record]

    From
        [$(val__source_path)] (qvd)
    ;

    Trace Commenting table...;
    Comment Table [peripheral__adventure_works__work_order_routings] With 'Work order details.';

    Trace Commenting fields...;
    Comment Field [_pit_hook__work_order_routing] With 'Point in time version of _hook__work_order_routing.';
    Comment Field [work_order_routing__work_order_id] With 'Primary key. Foreign key to WorkOrder.WorkOrderID.';
    Comment Field [work_order_routing__product_id] With 'Primary key. Foreign key to Product.ProductID.';
    Comment Field [work_order_routing__operation_sequence] With 'Primary key. Indicates the manufacturing process sequence.';
    Comment Field [work_order_routing__location_id] With 'Manufacturing location where the part is processed. Foreign key to Location.LocationID.';
    Comment Field [work_order_routing__scheduled_start_date] With 'Planned manufacturing start date.';
    Comment Field [work_order_routing__scheduled_end_date] With 'Planned manufacturing end date.';
    Comment Field [work_order_routing__actual_start_date] With 'Actual start date.';
    Comment Field [work_order_routing__actual_end_date] With 'Actual end date.';
    Comment Field [work_order_routing__actual_resource_hrs] With 'Number of manufacturing hours used.';
    Comment Field [work_order_routing__planned_cost] With 'Estimated manufacturing cost.';
    Comment Field [work_order_routing__actual_cost] With 'Actual manufacturing cost.';
    Comment Field [work_order_routing__modified_date] With 'Date and time the record was last updated.';
    Comment Field [work_order_routing__record_hash] With 'Hash of the record.';
    Comment Field [work_order_routing__record_loaded_at] With 'Date and time the record was loaded.';
    Comment Field [work_order_routing__record_updated_at] With 'Date and time the record was last updated.';
    Comment Field [work_order_routing__record_version] With 'Version of the record.';
    Comment Field [work_order_routing__record_valid_from] With 'Date and time the record was valid from.';
    Comment Field [work_order_routing__record_valid_to] With 'Date and time the record was valid to.';
    Comment Field [work_order_routing__is_current_record] With '1 if the record is current, 0 otherwise.';

    Trace Storing data...;
    Store [peripheral__adventure_works__work_order_routings] Into [$(val__target_path)] (qvd);

    Trace Dropping table...;
    Drop Table [peripheral__adventure_works__work_order_routings];

Else
    Trace Source is older than target, skipping...;

End If

Trace Resetting variables...;
Let val__source_path = Null();
Let val__target_path = Null();
Let val__source_create_time = Null();
Let val__target_create_time = Null();
Let val__source_is_newer = Null();
