Trace
---------------------------------------------------------------
    Defining peripheral__adventure_works__shopping_cart_items
---------------------------------------------------------------
;
Trace Setting variables...;
Let val__source_path = '$(val__qvd_path__dab)/frame__adventure_works__shopping_cart_items.qvd';
Let val__target_path = '$(val__qvd_path__dar)/peripheral__adventure_works__shopping_cart_items.qvd';
Let val__source_create_time = Timestamp(FileTime('$(val__source_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__target_create_time = Timestamp(FileTime('$(val__target_path)'), 'YYYY-MM-DD hh:mm:ss.fff');
Let val__source_is_newer = If('$(val__source_create_time)' > '$(val__target_create_time)', 1, 0);

Trace Checking if source is newer...;

If $(val__source_is_newer) = 1 Then 

    Trace Source is newer, loading & transforming data...;
    [peripheral__adventure_works__shopping_cart_items]:
    Load
        [_pit_hook__shopping_cart_item],
        [shopping_cart_item__shopping_cart_item_id],
        [shopping_cart_item__shopping_cart_id],
        [shopping_cart_item__quantity],
        [shopping_cart_item__product_id],
        [shopping_cart_item__date_created],
        [shopping_cart_item__modified_date],
        [shopping_cart_item__record_hash],
        [shopping_cart_item__record_loaded_at],
        [shopping_cart_item__record_updated_at],
        [shopping_cart_item__record_version],
        [shopping_cart_item__record_valid_from],
        [shopping_cart_item__record_valid_to],
        [shopping_cart_item__is_current_record]

    From
        [$(val__source_path)] (qvd)
    ;

    Trace Commenting table...;
    Comment Table [peripheral__adventure_works__shopping_cart_items] With 'Contains online customer orders until the order is submitted or cancelled.';

    Trace Commenting fields...;
    Comment Field [_pit_hook__shopping_cart_item] With 'Point in time hook for shopping_cart_item_id using keyset: reference__adventure_works.';
    Comment Field [shopping_cart_item__shopping_cart_item_id] With 'Primary key for ShoppingCartItem records.';
    Comment Field [shopping_cart_item__shopping_cart_id] With 'Shopping cart identification number.';
    Comment Field [shopping_cart_item__quantity] With 'Product quantity ordered.';
    Comment Field [shopping_cart_item__product_id] With 'Product ordered. Foreign key to Product.ProductID.';
    Comment Field [shopping_cart_item__date_created] With 'Date the time the record was created.';
    Comment Field [shopping_cart_item__modified_date] With 'Date and time the record was last updated.';
    Comment Field [shopping_cart_item__record_hash] With 'Hash of the record.';
    Comment Field [shopping_cart_item__record_loaded_at] With 'Date and time the record was loaded.';
    Comment Field [shopping_cart_item__record_updated_at] With 'Date and time the record was last updated.';
    Comment Field [shopping_cart_item__record_version] With 'Version of the record.';
    Comment Field [shopping_cart_item__record_valid_from] With 'Date and time the record was valid from.';
    Comment Field [shopping_cart_item__record_valid_to] With 'Date and time the record was valid to.';
    Comment Field [shopping_cart_item__is_current_record] With '1 if the record is current, 0 otherwise.';

    Trace Storing data...;
    Store [peripheral__adventure_works__shopping_cart_items] Into [$(val__target_path)] (qvd);

    Trace Dropping table...;
    Drop Table [peripheral__adventure_works__shopping_cart_items];

Else
    Trace Source is older than target, skipping...;

End If

Trace Resetting variables...;
Let val__source_path = Null();
Let val__target_path = Null();
Let val__source_create_time = Null();
Let val__target_create_time = Null();
Let val__source_is_newer = Null();
