Trace
===================================================================
    Data According To System
===================================================================
;

LIB CONNECT TO 'adventure_works__odata';

Trace
-------------------------------------------------------------------
    Extracting Addresses
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__addresses]:
LOAD
    Text([addressId]) AS [address_id], 
    Text([addressLine1]) AS [address_line1], 
    Text([addressLine2]) AS [address_line2], 
    Text([city]) AS [city], 
    Text([state]) AS [state], 
    Text([country]) AS [country], 
    Text([postalCode]) AS [postal_code], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    addressId,
    addressLine1,
    addressLine2,
    city,
    state,
    country,
    postalCode,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Addresses',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__addresses = '$(val__qvd_path__das)/raw__adventure_works__addresses.qvd';
TRACE Stored [raw__adventure_works__addresses] into [$(val__qvd_path__addresses)];
STORE [raw__adventure_works__addresses] INTO [$(val__qvd_path__addresses)] (qvd);
DROP TABLE [raw__adventure_works__addresses];


Trace
-------------------------------------------------------------------
    Extracting Address Types
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__address_types]:
LOAD
    Text([addressTypeId]) AS [address_type_id], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    addressTypeId,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='AddressTypes',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__address_types = '$(val__qvd_path__das)/raw__adventure_works__address_types.qvd';
TRACE Stored [raw__adventure_works__address_types] into [$(val__qvd_path__address_types)];
STORE [raw__adventure_works__address_types] INTO [$(val__qvd_path__address_types)] (qvd);
DROP TABLE [raw__adventure_works__address_types];


Trace
-------------------------------------------------------------------
    Extracting Bill Of Materials
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__bill_of_materials]:
LOAD
    Text([billOfMaterialsId]) AS [bill_of_materials_id], 
    Text([productAssemblyId]) AS [product_assembly_id], 
    Text([componentId]) AS [component_id], 
    Text([startDate]) AS [start_date], 
    Text([endDate]) AS [end_date], 
    Text([measurementUnit]) AS [measurement_unit], 
    Text([bomlevel]) AS [bomlevel], 
    Text([perAssemblyQuantity]) AS [per_assembly_quantity], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    billOfMaterialsId,
    productAssemblyId,
    componentId,
    startDate,
    endDate,
    measurementUnit,
    bomlevel,
    perAssemblyQuantity,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='BillOfMaterials',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__bill_of_materials = '$(val__qvd_path__das)/raw__adventure_works__bill_of_materials.qvd';
TRACE Stored [raw__adventure_works__bill_of_materials] into [$(val__qvd_path__bill_of_materials)];
STORE [raw__adventure_works__bill_of_materials] INTO [$(val__qvd_path__bill_of_materials)] (qvd);
DROP TABLE [raw__adventure_works__bill_of_materials];


Trace
-------------------------------------------------------------------
    Extracting Business Entities
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__business_entities]:
LOAD
    Text([businessEntityId]) AS [business_entity_id], 
    Text([address]) AS [address], 
    Text([addressType]) AS [address_type], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    businessEntityId,
    address,
    addressType,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='BusinessEntities',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__business_entities = '$(val__qvd_path__das)/raw__adventure_works__business_entities.qvd';
TRACE Stored [raw__adventure_works__business_entities] into [$(val__qvd_path__business_entities)];
STORE [raw__adventure_works__business_entities] INTO [$(val__qvd_path__business_entities)] (qvd);
DROP TABLE [raw__adventure_works__business_entities];


Trace
-------------------------------------------------------------------
    Extracting Business Entity Addresses
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__business_entity_addresses]:
LOAD
    Text([businessEntityId]) AS [business_entity_id], 
    Text([address]) AS [address], 
    Text([addressType]) AS [address_type], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    businessEntityId,
    address,
    addressType,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='BusinessEntityAddresses',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__business_entity_addresses = '$(val__qvd_path__das)/raw__adventure_works__business_entity_addresses.qvd';
TRACE Stored [raw__adventure_works__business_entity_addresses] into [$(val__qvd_path__business_entity_addresses)];
STORE [raw__adventure_works__business_entity_addresses] INTO [$(val__qvd_path__business_entity_addresses)] (qvd);
DROP TABLE [raw__adventure_works__business_entity_addresses];


Trace
-------------------------------------------------------------------
    Extracting Business Entity Contacts
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__business_entity_contacts]:
LOAD
    Text([businessEntityId]) AS [business_entity_id], 
    Text([personId]) AS [person_id], 
    Text([contactType]) AS [contact_type], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    businessEntityId,
    personId,
    contactType,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='BusinessEntityContacts',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__business_entity_contacts = '$(val__qvd_path__das)/raw__adventure_works__business_entity_contacts.qvd';
TRACE Stored [raw__adventure_works__business_entity_contacts] into [$(val__qvd_path__business_entity_contacts)];
STORE [raw__adventure_works__business_entity_contacts] INTO [$(val__qvd_path__business_entity_contacts)] (qvd);
DROP TABLE [raw__adventure_works__business_entity_contacts];


Trace
-------------------------------------------------------------------
    Extracting Contact Types
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__contact_types]:
LOAD
    Text([contactTypeId]) AS [contact_type_id], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    contactTypeId,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ContactTypes',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__contact_types = '$(val__qvd_path__das)/raw__adventure_works__contact_types.qvd';
TRACE Stored [raw__adventure_works__contact_types] into [$(val__qvd_path__contact_types)];
STORE [raw__adventure_works__contact_types] INTO [$(val__qvd_path__contact_types)] (qvd);
DROP TABLE [raw__adventure_works__contact_types];


Trace
-------------------------------------------------------------------
    Extracting Country Regions
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__country_regions]:
LOAD
    Text([countryRegionCode]) AS [country_region_code], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    countryRegionCode,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='CountryRegions',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__country_regions = '$(val__qvd_path__das)/raw__adventure_works__country_regions.qvd';
TRACE Stored [raw__adventure_works__country_regions] into [$(val__qvd_path__country_regions)];
STORE [raw__adventure_works__country_regions] INTO [$(val__qvd_path__country_regions)] (qvd);
DROP TABLE [raw__adventure_works__country_regions];


Trace
-------------------------------------------------------------------
    Extracting Credit Cards
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__credit_cards]:
LOAD
    Text([creditCardId]) AS [credit_card_id], 
    Text([cardType]) AS [card_type], 
    Text([cardNumber]) AS [card_number], 
    Text([expiryMonth]) AS [expiry_month], 
    Text([expiryYear]) AS [expiry_year], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    creditCardId,
    cardType,
    cardNumber,
    expiryMonth,
    expiryYear,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='CreditCards',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__credit_cards = '$(val__qvd_path__das)/raw__adventure_works__credit_cards.qvd';
TRACE Stored [raw__adventure_works__credit_cards] into [$(val__qvd_path__credit_cards)];
STORE [raw__adventure_works__credit_cards] INTO [$(val__qvd_path__credit_cards)] (qvd);
DROP TABLE [raw__adventure_works__credit_cards];


Trace
-------------------------------------------------------------------
    Extracting Cultures
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__cultures]:
LOAD
    Text([cultureId]) AS [culture_id], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    cultureId,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Cultures',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__cultures = '$(val__qvd_path__das)/raw__adventure_works__cultures.qvd';
TRACE Stored [raw__adventure_works__cultures] into [$(val__qvd_path__cultures)];
STORE [raw__adventure_works__cultures] INTO [$(val__qvd_path__cultures)] (qvd);
DROP TABLE [raw__adventure_works__cultures];


Trace
-------------------------------------------------------------------
    Extracting Currencies
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__currencies]:
LOAD
    Text([currencyCode]) AS [currency_code], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    currencyCode,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Currencies',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__currencies = '$(val__qvd_path__das)/raw__adventure_works__currencies.qvd';
TRACE Stored [raw__adventure_works__currencies] into [$(val__qvd_path__currencies)];
STORE [raw__adventure_works__currencies] INTO [$(val__qvd_path__currencies)] (qvd);
DROP TABLE [raw__adventure_works__currencies];


Trace
-------------------------------------------------------------------
    Extracting Currency Rates
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__currency_rates]:
LOAD
    Text([currencyRateId]) AS [currency_rate_id], 
    Text([currencyRateDate]) AS [currency_rate_date], 
    Text([fromCurrencyCode]) AS [from_currency_code], 
    Text([toCurrencyCode]) AS [to_currency_code], 
    Text([averageRate]) AS [average_rate], 
    Text([endOfDayRate]) AS [end_of_day_rate], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    currencyRateId,
    currencyRateDate,
    fromCurrencyCode,
    toCurrencyCode,
    averageRate,
    endOfDayRate,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='CurrencyRates',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__currency_rates = '$(val__qvd_path__das)/raw__adventure_works__currency_rates.qvd';
TRACE Stored [raw__adventure_works__currency_rates] into [$(val__qvd_path__currency_rates)];
STORE [raw__adventure_works__currency_rates] INTO [$(val__qvd_path__currency_rates)] (qvd);
DROP TABLE [raw__adventure_works__currency_rates];


Trace
-------------------------------------------------------------------
    Extracting Customers
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__customers]:
LOAD
    Text([customerId]) AS [customer_id], 
    Text([personId]) AS [person_id], 
    Text([storeId]) AS [store_id], 
    Text([territory]) AS [territory], 
    Text([accountNumber]) AS [account_number], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    customerId,
    personId,
    storeId,
    territory,
    accountNumber,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Customers',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__customers = '$(val__qvd_path__das)/raw__adventure_works__customers.qvd';
TRACE Stored [raw__adventure_works__customers] into [$(val__qvd_path__customers)];
STORE [raw__adventure_works__customers] INTO [$(val__qvd_path__customers)] (qvd);
DROP TABLE [raw__adventure_works__customers];


Trace
-------------------------------------------------------------------
    Extracting Departments
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__departments]:
LOAD
    Text([departmentId]) AS [department_id], 
    Text([name]) AS [name], 
    Text([groupName]) AS [group_name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    departmentId,
    name,
    groupName,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Departments',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__departments = '$(val__qvd_path__das)/raw__adventure_works__departments.qvd';
TRACE Stored [raw__adventure_works__departments] into [$(val__qvd_path__departments)];
STORE [raw__adventure_works__departments] INTO [$(val__qvd_path__departments)] (qvd);
DROP TABLE [raw__adventure_works__departments];


Trace
-------------------------------------------------------------------
    Extracting Email Addresses
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__email_addresses]:
LOAD
    Text([personId]) AS [person_id], 
    Text([emailAddressId]) AS [email_address_id], 
    Text([emailAddress]) AS [email_address], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    personId,
    emailAddressId,
    emailAddress,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='EmailAddresses',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__email_addresses = '$(val__qvd_path__das)/raw__adventure_works__email_addresses.qvd';
TRACE Stored [raw__adventure_works__email_addresses] into [$(val__qvd_path__email_addresses)];
STORE [raw__adventure_works__email_addresses] INTO [$(val__qvd_path__email_addresses)] (qvd);
DROP TABLE [raw__adventure_works__email_addresses];


Trace
-------------------------------------------------------------------
    Extracting Employees
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__employees]:
LOAD
    Text([employeeId]) AS [employee_id], 
    Text([nationalIdnumber]) AS [national_idnumber], 
    Text([loginId]) AS [login_id], 
    Text([organizationLevel]) AS [organization_level], 
    Text([jobTitle]) AS [job_title], 
    Text([birthDate]) AS [birth_date], 
    Text([maritalStatus]) AS [marital_status], 
    Text([gender]) AS [gender], 
    Text([hireDate]) AS [hire_date], 
    Text([isSalaried]) AS [is_salaried], 
    Text([vacationHours]) AS [vacation_hours], 
    Text([sickLeaveHours]) AS [sick_leave_hours], 
    Text([isActive]) AS [is_active], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    employeeId,
    nationalIdnumber,
    loginId,
    organizationLevel,
    jobTitle,
    birthDate,
    maritalStatus,
    gender,
    hireDate,
    isSalaried,
    vacationHours,
    sickLeaveHours,
    isActive,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Employees',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__employees = '$(val__qvd_path__das)/raw__adventure_works__employees.qvd';
TRACE Stored [raw__adventure_works__employees] into [$(val__qvd_path__employees)];
STORE [raw__adventure_works__employees] INTO [$(val__qvd_path__employees)] (qvd);
DROP TABLE [raw__adventure_works__employees];


Trace
-------------------------------------------------------------------
    Extracting Illustrations
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__illustrations]:
LOAD
    Text([illustrationId]) AS [illustration_id], 
    Text([diagram]) AS [diagram], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    illustrationId,
    diagram,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Illustrations',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__illustrations = '$(val__qvd_path__das)/raw__adventure_works__illustrations.qvd';
TRACE Stored [raw__adventure_works__illustrations] into [$(val__qvd_path__illustrations)];
STORE [raw__adventure_works__illustrations] INTO [$(val__qvd_path__illustrations)] (qvd);
DROP TABLE [raw__adventure_works__illustrations];


Trace
-------------------------------------------------------------------
    Extracting Job Candidates
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__job_candidates]:
LOAD
    Text([jobCandidateId]) AS [job_candidate_id], 
    Text([employeeId]) AS [employee_id], 
    Text([resume]) AS [resume], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    jobCandidateId,
    employeeId,
    resume,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='JobCandidates',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__job_candidates = '$(val__qvd_path__das)/raw__adventure_works__job_candidates.qvd';
TRACE Stored [raw__adventure_works__job_candidates] into [$(val__qvd_path__job_candidates)];
STORE [raw__adventure_works__job_candidates] INTO [$(val__qvd_path__job_candidates)] (qvd);
DROP TABLE [raw__adventure_works__job_candidates];


Trace
-------------------------------------------------------------------
    Extracting Locations
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__locations]:
LOAD
    Text([locationId]) AS [location_id], 
    Text([name]) AS [name], 
    Text([costRate]) AS [cost_rate], 
    Text([availability]) AS [availability], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    locationId,
    name,
    costRate,
    availability,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Locations',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__locations = '$(val__qvd_path__das)/raw__adventure_works__locations.qvd';
TRACE Stored [raw__adventure_works__locations] into [$(val__qvd_path__locations)];
STORE [raw__adventure_works__locations] INTO [$(val__qvd_path__locations)] (qvd);
DROP TABLE [raw__adventure_works__locations];


Trace
-------------------------------------------------------------------
    Extracting Person Phones
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__person_phones]:
LOAD
    Text([personId]) AS [person_id], 
    Text([personType]) AS [person_type], 
    Text([nameStyle]) AS [name_style], 
    Text([title]) AS [title], 
    Text([firstName]) AS [first_name], 
    Text([middleName]) AS [middle_name], 
    Text([lastName]) AS [last_name], 
    Text([suffix]) AS [suffix], 
    Text([emailPromotion]) AS [email_promotion], 
    Text([additionalContactInfo]) AS [additional_contact_info], 
    Text([demographics]) AS [demographics], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    personId,
    personType,
    nameStyle,
    title,
    firstName,
    middleName,
    lastName,
    suffix,
    emailPromotion,
    additionalContactInfo,
    demographics,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='PersonPhones',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__person_phones = '$(val__qvd_path__das)/raw__adventure_works__person_phones.qvd';
TRACE Stored [raw__adventure_works__person_phones] into [$(val__qvd_path__person_phones)];
STORE [raw__adventure_works__person_phones] INTO [$(val__qvd_path__person_phones)] (qvd);
DROP TABLE [raw__adventure_works__person_phones];


Trace
-------------------------------------------------------------------
    Extracting Persons
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__persons]:
LOAD
    Text([businessEntityId]) AS [business_entity_id], 
    Text([personId]) AS [person_id], 
    Text([contactType]) AS [contact_type], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    businessEntityId,
    personId,
    contactType,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Persons',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__persons = '$(val__qvd_path__das)/raw__adventure_works__persons.qvd';
TRACE Stored [raw__adventure_works__persons] into [$(val__qvd_path__persons)];
STORE [raw__adventure_works__persons] INTO [$(val__qvd_path__persons)] (qvd);
DROP TABLE [raw__adventure_works__persons];


Trace
-------------------------------------------------------------------
    Extracting Phone Number Types
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__phone_number_types]:
LOAD
    Text([phoneNumberTypeId]) AS [phone_number_type_id], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    phoneNumberTypeId,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='PhoneNumberTypes',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__phone_number_types = '$(val__qvd_path__das)/raw__adventure_works__phone_number_types.qvd';
TRACE Stored [raw__adventure_works__phone_number_types] into [$(val__qvd_path__phone_number_types)];
STORE [raw__adventure_works__phone_number_types] INTO [$(val__qvd_path__phone_number_types)] (qvd);
DROP TABLE [raw__adventure_works__phone_number_types];


Trace
-------------------------------------------------------------------
    Extracting Product Categories
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_categories]:
LOAD
    Text([productCategoryId]) AS [product_category_id], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productCategoryId,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductCategories',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_categories = '$(val__qvd_path__das)/raw__adventure_works__product_categories.qvd';
TRACE Stored [raw__adventure_works__product_categories] into [$(val__qvd_path__product_categories)];
STORE [raw__adventure_works__product_categories] INTO [$(val__qvd_path__product_categories)] (qvd);
DROP TABLE [raw__adventure_works__product_categories];


Trace
-------------------------------------------------------------------
    Extracting Product Cost Histories
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_cost_histories]:
LOAD
    Text([productId]) AS [product_id], 
    Text([startDate]) AS [start_date], 
    Text([endDate]) AS [end_date], 
    Text([standardCost]) AS [standard_cost], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productId,
    startDate,
    endDate,
    standardCost,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductCostHistories',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_cost_histories = '$(val__qvd_path__das)/raw__adventure_works__product_cost_histories.qvd';
TRACE Stored [raw__adventure_works__product_cost_histories] into [$(val__qvd_path__product_cost_histories)];
STORE [raw__adventure_works__product_cost_histories] INTO [$(val__qvd_path__product_cost_histories)] (qvd);
DROP TABLE [raw__adventure_works__product_cost_histories];


Trace
-------------------------------------------------------------------
    Extracting Product Descriptions
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_descriptions]:
LOAD
    Text([productDescriptionId]) AS [product_description_id], 
    Text([description]) AS [description], 
    Text([cultureCode]) AS [culture_code], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productDescriptionId,
    description,
    cultureCode,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductDescriptions',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_descriptions = '$(val__qvd_path__das)/raw__adventure_works__product_descriptions.qvd';
TRACE Stored [raw__adventure_works__product_descriptions] into [$(val__qvd_path__product_descriptions)];
STORE [raw__adventure_works__product_descriptions] INTO [$(val__qvd_path__product_descriptions)] (qvd);
DROP TABLE [raw__adventure_works__product_descriptions];


Trace
-------------------------------------------------------------------
    Extracting Product Inventories
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_inventories]:
LOAD
    Text([locationId]) AS [location_id], 
    Text([name]) AS [name], 
    Text([costRate]) AS [cost_rate], 
    Text([availability]) AS [availability], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    locationId,
    name,
    costRate,
    availability,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductInventories',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_inventories = '$(val__qvd_path__das)/raw__adventure_works__product_inventories.qvd';
TRACE Stored [raw__adventure_works__product_inventories] into [$(val__qvd_path__product_inventories)];
STORE [raw__adventure_works__product_inventories] INTO [$(val__qvd_path__product_inventories)] (qvd);
DROP TABLE [raw__adventure_works__product_inventories];


Trace
-------------------------------------------------------------------
    Extracting Product List Price Histories
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_list_price_histories]:
LOAD
    Text([productId]) AS [product_id], 
    Text([name]) AS [name], 
    Text([productNumber]) AS [product_number], 
    Text([isManufactured]) AS [is_manufactured], 
    Text([isSaleable]) AS [is_saleable], 
    Text([color]) AS [color], 
    Text([safetyStockLevel]) AS [safety_stock_level], 
    Text([reorderPoint]) AS [reorder_point], 
    Text([standardCost]) AS [standard_cost], 
    Text([listPrice]) AS [list_price], 
    Text([size]) AS [size], 
    Text([sizeUnit]) AS [size_unit], 
    Text([weightUnit]) AS [weight_unit], 
    Text([weight]) AS [weight], 
    Text([daysToManufacture]) AS [days_to_manufacture], 
    Text([productLine]) AS [product_line], 
    Text([class]) AS [class], 
    Text([style]) AS [style], 
    Text([subcategory]) AS [subcategory], 
    Text([category]) AS [category], 
    Text([model]) AS [model], 
    Text([sellStartDate]) AS [sell_start_date], 
    Text([sellEndDate]) AS [sell_end_date], 
    Text([discontinuedDate]) AS [discontinued_date], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productId,
    name,
    productNumber,
    isManufactured,
    isSaleable,
    color,
    safetyStockLevel,
    reorderPoint,
    standardCost,
    listPrice,
    size,
    sizeUnit,
    weightUnit,
    weight,
    daysToManufacture,
    productLine,
    class,
    style,
    subcategory,
    category,
    model,
    sellStartDate,
    sellEndDate,
    discontinuedDate,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductListPriceHistories',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_list_price_histories = '$(val__qvd_path__das)/raw__adventure_works__product_list_price_histories.qvd';
TRACE Stored [raw__adventure_works__product_list_price_histories] into [$(val__qvd_path__product_list_price_histories)];
STORE [raw__adventure_works__product_list_price_histories] INTO [$(val__qvd_path__product_list_price_histories)] (qvd);
DROP TABLE [raw__adventure_works__product_list_price_histories];


Trace
-------------------------------------------------------------------
    Extracting Product Model Illustrations
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_model_illustrations]:
LOAD
    Text([illustrationId]) AS [illustration_id], 
    Text([diagram]) AS [diagram], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    illustrationId,
    diagram,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductModelIllustrations',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_model_illustrations = '$(val__qvd_path__das)/raw__adventure_works__product_model_illustrations.qvd';
TRACE Stored [raw__adventure_works__product_model_illustrations] into [$(val__qvd_path__product_model_illustrations)];
STORE [raw__adventure_works__product_model_illustrations] INTO [$(val__qvd_path__product_model_illustrations)] (qvd);
DROP TABLE [raw__adventure_works__product_model_illustrations];


Trace
-------------------------------------------------------------------
    Extracting Product Models
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_models]:
LOAD
    Text([productModelId]) AS [product_model_id], 
    Text([name]) AS [name], 
    Text([catalogDescription]) AS [catalog_description], 
    Text([instructions]) AS [instructions], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productModelId,
    name,
    catalogDescription,
    instructions,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductModels',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_models = '$(val__qvd_path__das)/raw__adventure_works__product_models.qvd';
TRACE Stored [raw__adventure_works__product_models] into [$(val__qvd_path__product_models)];
STORE [raw__adventure_works__product_models] INTO [$(val__qvd_path__product_models)] (qvd);
DROP TABLE [raw__adventure_works__product_models];


Trace
-------------------------------------------------------------------
    Extracting Product Photos
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_photos]:
LOAD
    Text([productPhotoId]) AS [product_photo_id], 
    Text([thumbNailPhoto]) AS [thumb_nail_photo], 
    Text([thumbnailPhotoFileName]) AS [thumbnail_photo_file_name], 
    Text([largePhoto]) AS [large_photo], 
    Text([largePhotoFileName]) AS [large_photo_file_name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productPhotoId,
    thumbNailPhoto,
    thumbnailPhotoFileName,
    largePhoto,
    largePhotoFileName,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductPhotos',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_photos = '$(val__qvd_path__das)/raw__adventure_works__product_photos.qvd';
TRACE Stored [raw__adventure_works__product_photos] into [$(val__qvd_path__product_photos)];
STORE [raw__adventure_works__product_photos] INTO [$(val__qvd_path__product_photos)] (qvd);
DROP TABLE [raw__adventure_works__product_photos];


Trace
-------------------------------------------------------------------
    Extracting Product Reviews
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_reviews]:
LOAD
    Text([productId]) AS [product_id], 
    Text([name]) AS [name], 
    Text([productNumber]) AS [product_number], 
    Text([isManufactured]) AS [is_manufactured], 
    Text([isSaleable]) AS [is_saleable], 
    Text([color]) AS [color], 
    Text([safetyStockLevel]) AS [safety_stock_level], 
    Text([reorderPoint]) AS [reorder_point], 
    Text([standardCost]) AS [standard_cost], 
    Text([listPrice]) AS [list_price], 
    Text([size]) AS [size], 
    Text([sizeUnit]) AS [size_unit], 
    Text([weightUnit]) AS [weight_unit], 
    Text([weight]) AS [weight], 
    Text([daysToManufacture]) AS [days_to_manufacture], 
    Text([productLine]) AS [product_line], 
    Text([class]) AS [class], 
    Text([style]) AS [style], 
    Text([subcategory]) AS [subcategory], 
    Text([category]) AS [category], 
    Text([model]) AS [model], 
    Text([sellStartDate]) AS [sell_start_date], 
    Text([sellEndDate]) AS [sell_end_date], 
    Text([discontinuedDate]) AS [discontinued_date], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productId,
    name,
    productNumber,
    isManufactured,
    isSaleable,
    color,
    safetyStockLevel,
    reorderPoint,
    standardCost,
    listPrice,
    size,
    sizeUnit,
    weightUnit,
    weight,
    daysToManufacture,
    productLine,
    class,
    style,
    subcategory,
    category,
    model,
    sellStartDate,
    sellEndDate,
    discontinuedDate,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductReviews',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_reviews = '$(val__qvd_path__das)/raw__adventure_works__product_reviews.qvd';
TRACE Stored [raw__adventure_works__product_reviews] into [$(val__qvd_path__product_reviews)];
STORE [raw__adventure_works__product_reviews] INTO [$(val__qvd_path__product_reviews)] (qvd);
DROP TABLE [raw__adventure_works__product_reviews];


Trace
-------------------------------------------------------------------
    Extracting Products
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__products]:
LOAD
    Text([productId]) AS [product_id], 
    Text([name]) AS [name], 
    Text([productNumber]) AS [product_number], 
    Text([isManufactured]) AS [is_manufactured], 
    Text([isSaleable]) AS [is_saleable], 
    Text([color]) AS [color], 
    Text([safetyStockLevel]) AS [safety_stock_level], 
    Text([reorderPoint]) AS [reorder_point], 
    Text([standardCost]) AS [standard_cost], 
    Text([listPrice]) AS [list_price], 
    Text([size]) AS [size], 
    Text([sizeUnit]) AS [size_unit], 
    Text([weightUnit]) AS [weight_unit], 
    Text([weight]) AS [weight], 
    Text([daysToManufacture]) AS [days_to_manufacture], 
    Text([productLine]) AS [product_line], 
    Text([class]) AS [class], 
    Text([style]) AS [style], 
    Text([subcategory]) AS [subcategory], 
    Text([category]) AS [category], 
    Text([model]) AS [model], 
    Text([sellStartDate]) AS [sell_start_date], 
    Text([sellEndDate]) AS [sell_end_date], 
    Text([discontinuedDate]) AS [discontinued_date], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productId,
    name,
    productNumber,
    isManufactured,
    isSaleable,
    color,
    safetyStockLevel,
    reorderPoint,
    standardCost,
    listPrice,
    size,
    sizeUnit,
    weightUnit,
    weight,
    daysToManufacture,
    productLine,
    class,
    style,
    subcategory,
    category,
    model,
    sellStartDate,
    sellEndDate,
    discontinuedDate,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Products',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__products = '$(val__qvd_path__das)/raw__adventure_works__products.qvd';
TRACE Stored [raw__adventure_works__products] into [$(val__qvd_path__products)];
STORE [raw__adventure_works__products] INTO [$(val__qvd_path__products)] (qvd);
DROP TABLE [raw__adventure_works__products];


Trace
-------------------------------------------------------------------
    Extracting Product Subcategories
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_subcategories]:
LOAD
    Text([productCategoryId]) AS [product_category_id], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productCategoryId,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductSubcategories',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_subcategories = '$(val__qvd_path__das)/raw__adventure_works__product_subcategories.qvd';
TRACE Stored [raw__adventure_works__product_subcategories] into [$(val__qvd_path__product_subcategories)];
STORE [raw__adventure_works__product_subcategories] INTO [$(val__qvd_path__product_subcategories)] (qvd);
DROP TABLE [raw__adventure_works__product_subcategories];


Trace
-------------------------------------------------------------------
    Extracting Product Vendors
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__product_vendors]:
LOAD
    Text([productId]) AS [product_id], 
    Text([vendorId]) AS [vendor_id], 
    Text([averageLeadTime]) AS [average_lead_time], 
    Text([standardPrice]) AS [standard_price], 
    Text([lastReceiptCost]) AS [last_receipt_cost], 
    Text([lastReceiptDate]) AS [last_receipt_date], 
    Text([minOrderQuantity]) AS [min_order_quantity], 
    Text([maxOrderQuantity]) AS [max_order_quantity], 
    Text([onOrderQuantity]) AS [on_order_quantity], 
    Text([measurementUnit]) AS [measurement_unit], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productId,
    vendorId,
    averageLeadTime,
    standardPrice,
    lastReceiptCost,
    lastReceiptDate,
    minOrderQuantity,
    maxOrderQuantity,
    onOrderQuantity,
    measurementUnit,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ProductVendors',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__product_vendors = '$(val__qvd_path__das)/raw__adventure_works__product_vendors.qvd';
TRACE Stored [raw__adventure_works__product_vendors] into [$(val__qvd_path__product_vendors)];
STORE [raw__adventure_works__product_vendors] INTO [$(val__qvd_path__product_vendors)] (qvd);
DROP TABLE [raw__adventure_works__product_vendors];


Trace
-------------------------------------------------------------------
    Extracting Purchase Order Details
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__purchase_order_details]:
LOAD
    Text([purchaseOrderId]) AS [purchase_order_id], 
    Text([purchaseOrderDetailId]) AS [purchase_order_detail_id], 
    Text([dueDate]) AS [due_date], 
    Text([orderQuantity]) AS [order_quantity], 
    Text([productId]) AS [product_id], 
    Text([unitPrice]) AS [unit_price], 
    Text([lineTotal]) AS [line_total], 
    Text([receivedQuantity]) AS [received_quantity], 
    Text([rejectedQuantity]) AS [rejected_quantity], 
    Text([stockedQuantity]) AS [stocked_quantity], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    purchaseOrderId,
    purchaseOrderDetailId,
    dueDate,
    orderQuantity,
    productId,
    unitPrice,
    lineTotal,
    receivedQuantity,
    rejectedQuantity,
    stockedQuantity,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='PurchaseOrderDetails',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__purchase_order_details = '$(val__qvd_path__das)/raw__adventure_works__purchase_order_details.qvd';
TRACE Stored [raw__adventure_works__purchase_order_details] into [$(val__qvd_path__purchase_order_details)];
STORE [raw__adventure_works__purchase_order_details] INTO [$(val__qvd_path__purchase_order_details)] (qvd);
DROP TABLE [raw__adventure_works__purchase_order_details];


Trace
-------------------------------------------------------------------
    Extracting Purchase Order Headers
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__purchase_order_headers]:
LOAD
    Text([purchaseOrderId]) AS [purchase_order_id], 
    Text([revisionNumber]) AS [revision_number], 
    Text([status]) AS [status], 
    Text([employeeId]) AS [employee_id], 
    Text([vendor]) AS [vendor], 
    Text([shipMethod]) AS [ship_method], 
    Text([orderDate]) AS [order_date], 
    Text([shipDate]) AS [ship_date], 
    Text([subTotal]) AS [sub_total], 
    Text([taxAmount]) AS [tax_amount], 
    Text([freight]) AS [freight], 
    Text([totalDue]) AS [total_due], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    purchaseOrderId,
    revisionNumber,
    status,
    employeeId,
    vendor,
    shipMethod,
    orderDate,
    shipDate,
    subTotal,
    taxAmount,
    freight,
    totalDue,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='PurchaseOrderHeaders',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__purchase_order_headers = '$(val__qvd_path__das)/raw__adventure_works__purchase_order_headers.qvd';
TRACE Stored [raw__adventure_works__purchase_order_headers] into [$(val__qvd_path__purchase_order_headers)];
STORE [raw__adventure_works__purchase_order_headers] INTO [$(val__qvd_path__purchase_order_headers)] (qvd);
DROP TABLE [raw__adventure_works__purchase_order_headers];


Trace
-------------------------------------------------------------------
    Extracting Sales Order Details
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__sales_order_details]:
LOAD
    Text([salesOrderId]) AS [sales_order_id], 
    Text([salesOrderDetailId]) AS [sales_order_detail_id], 
    Text([carrierTrackingNumber]) AS [carrier_tracking_number], 
    Text([orderQuantity]) AS [order_quantity], 
    Text([productId]) AS [product_id], 
    Text([productName]) AS [product_name], 
    Text([specialOfferId]) AS [special_offer_id], 
    Text([unitPrice]) AS [unit_price], 
    Text([unitPriceDiscount]) AS [unit_price_discount], 
    Text([lineTotal]) AS [line_total], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    salesOrderId,
    salesOrderDetailId,
    carrierTrackingNumber,
    orderQuantity,
    productId,
    productName,
    specialOfferId,
    unitPrice,
    unitPriceDiscount,
    lineTotal,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='SalesOrderDetails',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__sales_order_details = '$(val__qvd_path__das)/raw__adventure_works__sales_order_details.qvd';
TRACE Stored [raw__adventure_works__sales_order_details] into [$(val__qvd_path__sales_order_details)];
STORE [raw__adventure_works__sales_order_details] INTO [$(val__qvd_path__sales_order_details)] (qvd);
DROP TABLE [raw__adventure_works__sales_order_details];


Trace
-------------------------------------------------------------------
    Extracting Sales Order Headers
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__sales_order_headers]:
LOAD
    Text([salesOrderId]) AS [sales_order_id], 
    Text([revisionNumber]) AS [revision_number], 
    Text([orderDate]) AS [order_date], 
    Text([dueDate]) AS [due_date], 
    Text([shipDate]) AS [ship_date], 
    Text([status]) AS [status], 
    Text([isOrderedOnline]) AS [is_ordered_online], 
    Text([salesOrderNumber]) AS [sales_order_number], 
    Text([purchaseOrderNumber]) AS [purchase_order_number], 
    Text([accountNumber]) AS [account_number], 
    Text([customerId]) AS [customer_id], 
    Text([salesPersonId]) AS [sales_person_id], 
    Text([territory]) AS [territory], 
    Text([billToAddress]) AS [bill_to_address], 
    Text([shipToAddress]) AS [ship_to_address], 
    Text([shipMethod]) AS [ship_method], 
    Text([creditCardId]) AS [credit_card_id], 
    Text([creditCardApprovalCode]) AS [credit_card_approval_code], 
    Text([currencyRateId]) AS [currency_rate_id], 
    Text([subTotal]) AS [sub_total], 
    Text([taxAmount]) AS [tax_amount], 
    Text([freight]) AS [freight], 
    Text([totalDue]) AS [total_due], 
    Text([comment]) AS [comment], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    salesOrderId,
    revisionNumber,
    orderDate,
    dueDate,
    shipDate,
    status,
    isOrderedOnline,
    salesOrderNumber,
    purchaseOrderNumber,
    accountNumber,
    customerId,
    salesPersonId,
    territory,
    billToAddress,
    shipToAddress,
    shipMethod,
    creditCardId,
    creditCardApprovalCode,
    currencyRateId,
    subTotal,
    taxAmount,
    freight,
    totalDue,
    comment,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='SalesOrderHeaders',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__sales_order_headers = '$(val__qvd_path__das)/raw__adventure_works__sales_order_headers.qvd';
TRACE Stored [raw__adventure_works__sales_order_headers] into [$(val__qvd_path__sales_order_headers)];
STORE [raw__adventure_works__sales_order_headers] INTO [$(val__qvd_path__sales_order_headers)] (qvd);
DROP TABLE [raw__adventure_works__sales_order_headers];


Trace
-------------------------------------------------------------------
    Extracting Sales Person Quota Histories
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__sales_person_quota_histories]:
LOAD
    Text([salesPersonId]) AS [sales_person_id], 
    Text([quotaDate]) AS [quota_date], 
    Text([salesQuota]) AS [sales_quota], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    salesPersonId,
    quotaDate,
    salesQuota,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='SalesPersonQuotaHistories',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__sales_person_quota_histories = '$(val__qvd_path__das)/raw__adventure_works__sales_person_quota_histories.qvd';
TRACE Stored [raw__adventure_works__sales_person_quota_histories] into [$(val__qvd_path__sales_person_quota_histories)];
STORE [raw__adventure_works__sales_person_quota_histories] INTO [$(val__qvd_path__sales_person_quota_histories)] (qvd);
DROP TABLE [raw__adventure_works__sales_person_quota_histories];


Trace
-------------------------------------------------------------------
    Extracting Sales Persons
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__sales_persons]:
LOAD
    Text([salesPersonId]) AS [sales_person_id], 
    Text([territory]) AS [territory], 
    Text([salesQuota]) AS [sales_quota], 
    Text([bonus]) AS [bonus], 
    Text([percentCommision]) AS [percent_commision], 
    Text([salesYtd]) AS [sales_ytd], 
    Text([salesLastYear]) AS [sales_last_year], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    salesPersonId,
    territory,
    salesQuota,
    bonus,
    percentCommision,
    salesYtd,
    salesLastYear,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='SalesPersons',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__sales_persons = '$(val__qvd_path__das)/raw__adventure_works__sales_persons.qvd';
TRACE Stored [raw__adventure_works__sales_persons] into [$(val__qvd_path__sales_persons)];
STORE [raw__adventure_works__sales_persons] INTO [$(val__qvd_path__sales_persons)] (qvd);
DROP TABLE [raw__adventure_works__sales_persons];


Trace
-------------------------------------------------------------------
    Extracting Sales Reasons
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__sales_reasons]:
LOAD
    Text([salesOrderId]) AS [sales_order_id], 
    Text([revisionNumber]) AS [revision_number], 
    Text([orderDate]) AS [order_date], 
    Text([dueDate]) AS [due_date], 
    Text([shipDate]) AS [ship_date], 
    Text([status]) AS [status], 
    Text([isOrderedOnline]) AS [is_ordered_online], 
    Text([salesOrderNumber]) AS [sales_order_number], 
    Text([purchaseOrderNumber]) AS [purchase_order_number], 
    Text([accountNumber]) AS [account_number], 
    Text([customerId]) AS [customer_id], 
    Text([salesPersonId]) AS [sales_person_id], 
    Text([territory]) AS [territory], 
    Text([billToAddress]) AS [bill_to_address], 
    Text([shipToAddress]) AS [ship_to_address], 
    Text([shipMethod]) AS [ship_method], 
    Text([creditCardId]) AS [credit_card_id], 
    Text([creditCardApprovalCode]) AS [credit_card_approval_code], 
    Text([currencyRateId]) AS [currency_rate_id], 
    Text([subTotal]) AS [sub_total], 
    Text([taxAmount]) AS [tax_amount], 
    Text([freight]) AS [freight], 
    Text([totalDue]) AS [total_due], 
    Text([comment]) AS [comment], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    salesOrderId,
    revisionNumber,
    orderDate,
    dueDate,
    shipDate,
    status,
    isOrderedOnline,
    salesOrderNumber,
    purchaseOrderNumber,
    accountNumber,
    customerId,
    salesPersonId,
    territory,
    billToAddress,
    shipToAddress,
    shipMethod,
    creditCardId,
    creditCardApprovalCode,
    currencyRateId,
    subTotal,
    taxAmount,
    freight,
    totalDue,
    comment,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='SalesReasons',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__sales_reasons = '$(val__qvd_path__das)/raw__adventure_works__sales_reasons.qvd';
TRACE Stored [raw__adventure_works__sales_reasons] into [$(val__qvd_path__sales_reasons)];
STORE [raw__adventure_works__sales_reasons] INTO [$(val__qvd_path__sales_reasons)] (qvd);
DROP TABLE [raw__adventure_works__sales_reasons];


Trace
-------------------------------------------------------------------
    Extracting Sales Tax Rates
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__sales_tax_rates]:
LOAD
    Text([salesTaxRateId]) AS [sales_tax_rate_id], 
    Text([stateProvince]) AS [state_province], 
    Text([taxType]) AS [tax_type], 
    Text([taxRate]) AS [tax_rate], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    salesTaxRateId,
    stateProvince,
    taxType,
    taxRate,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='SalesTaxRates',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__sales_tax_rates = '$(val__qvd_path__das)/raw__adventure_works__sales_tax_rates.qvd';
TRACE Stored [raw__adventure_works__sales_tax_rates] into [$(val__qvd_path__sales_tax_rates)];
STORE [raw__adventure_works__sales_tax_rates] INTO [$(val__qvd_path__sales_tax_rates)] (qvd);
DROP TABLE [raw__adventure_works__sales_tax_rates];


Trace
-------------------------------------------------------------------
    Extracting Sales Territories
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__sales_territories]:
LOAD
    Text([countryRegionCode]) AS [country_region_code], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    countryRegionCode,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='SalesTerritories',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__sales_territories = '$(val__qvd_path__das)/raw__adventure_works__sales_territories.qvd';
TRACE Stored [raw__adventure_works__sales_territories] into [$(val__qvd_path__sales_territories)];
STORE [raw__adventure_works__sales_territories] INTO [$(val__qvd_path__sales_territories)] (qvd);
DROP TABLE [raw__adventure_works__sales_territories];


Trace
-------------------------------------------------------------------
    Extracting Sales Territory Histories
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__sales_territory_histories]:
LOAD
    Text([salesPersonId]) AS [sales_person_id], 
    Text([territoryId]) AS [territory_id], 
    Text([startDate]) AS [start_date], 
    Text([endDate]) AS [end_date], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    salesPersonId,
    territoryId,
    startDate,
    endDate,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='SalesTerritoryHistories',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__sales_territory_histories = '$(val__qvd_path__das)/raw__adventure_works__sales_territory_histories.qvd';
TRACE Stored [raw__adventure_works__sales_territory_histories] into [$(val__qvd_path__sales_territory_histories)];
STORE [raw__adventure_works__sales_territory_histories] INTO [$(val__qvd_path__sales_territory_histories)] (qvd);
DROP TABLE [raw__adventure_works__sales_territory_histories];


Trace
-------------------------------------------------------------------
    Extracting Scrap Reasons
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__scrap_reasons]:
LOAD
    Text([scrapReasonId]) AS [scrap_reason_id], 
    Text([name]) AS [name], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    scrapReasonId,
    name,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ScrapReasons',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__scrap_reasons = '$(val__qvd_path__das)/raw__adventure_works__scrap_reasons.qvd';
TRACE Stored [raw__adventure_works__scrap_reasons] into [$(val__qvd_path__scrap_reasons)];
STORE [raw__adventure_works__scrap_reasons] INTO [$(val__qvd_path__scrap_reasons)] (qvd);
DROP TABLE [raw__adventure_works__scrap_reasons];


Trace
-------------------------------------------------------------------
    Extracting Shifts
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__shifts]:
LOAD
    Text([shiftId]) AS [shift_id], 
    Text([name]) AS [name], 
    Text([startTime]) AS [start_time], 
    Text([endTime]) AS [end_time], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    shiftId,
    name,
    startTime,
    endTime,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Shifts',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__shifts = '$(val__qvd_path__das)/raw__adventure_works__shifts.qvd';
TRACE Stored [raw__adventure_works__shifts] into [$(val__qvd_path__shifts)];
STORE [raw__adventure_works__shifts] INTO [$(val__qvd_path__shifts)] (qvd);
DROP TABLE [raw__adventure_works__shifts];


Trace
-------------------------------------------------------------------
    Extracting Ship Methods
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__ship_methods]:
LOAD
    Text([shipMethodId]) AS [ship_method_id], 
    Text([name]) AS [name], 
    Text([shipBase]) AS [ship_base], 
    Text([shipRate]) AS [ship_rate], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    shipMethodId,
    name,
    shipBase,
    shipRate,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ShipMethods',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__ship_methods = '$(val__qvd_path__das)/raw__adventure_works__ship_methods.qvd';
TRACE Stored [raw__adventure_works__ship_methods] into [$(val__qvd_path__ship_methods)];
STORE [raw__adventure_works__ship_methods] INTO [$(val__qvd_path__ship_methods)] (qvd);
DROP TABLE [raw__adventure_works__ship_methods];


Trace
-------------------------------------------------------------------
    Extracting Shopping Cart Items
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__shopping_cart_items]:
LOAD
    Text([productId]) AS [product_id], 
    Text([name]) AS [name], 
    Text([productNumber]) AS [product_number], 
    Text([isManufactured]) AS [is_manufactured], 
    Text([isSaleable]) AS [is_saleable], 
    Text([color]) AS [color], 
    Text([safetyStockLevel]) AS [safety_stock_level], 
    Text([reorderPoint]) AS [reorder_point], 
    Text([standardCost]) AS [standard_cost], 
    Text([listPrice]) AS [list_price], 
    Text([size]) AS [size], 
    Text([sizeUnit]) AS [size_unit], 
    Text([weightUnit]) AS [weight_unit], 
    Text([weight]) AS [weight], 
    Text([daysToManufacture]) AS [days_to_manufacture], 
    Text([productLine]) AS [product_line], 
    Text([class]) AS [class], 
    Text([style]) AS [style], 
    Text([subcategory]) AS [subcategory], 
    Text([category]) AS [category], 
    Text([model]) AS [model], 
    Text([sellStartDate]) AS [sell_start_date], 
    Text([sellEndDate]) AS [sell_end_date], 
    Text([discontinuedDate]) AS [discontinued_date], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productId,
    name,
    productNumber,
    isManufactured,
    isSaleable,
    color,
    safetyStockLevel,
    reorderPoint,
    standardCost,
    listPrice,
    size,
    sizeUnit,
    weightUnit,
    weight,
    daysToManufacture,
    productLine,
    class,
    style,
    subcategory,
    category,
    model,
    sellStartDate,
    sellEndDate,
    discontinuedDate,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='ShoppingCartItems',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__shopping_cart_items = '$(val__qvd_path__das)/raw__adventure_works__shopping_cart_items.qvd';
TRACE Stored [raw__adventure_works__shopping_cart_items] into [$(val__qvd_path__shopping_cart_items)];
STORE [raw__adventure_works__shopping_cart_items] INTO [$(val__qvd_path__shopping_cart_items)] (qvd);
DROP TABLE [raw__adventure_works__shopping_cart_items];


Trace
-------------------------------------------------------------------
    Extracting Special Offers
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__special_offers]:
LOAD
    Text([productId]) AS [product_id], 
    Text([name]) AS [name], 
    Text([productNumber]) AS [product_number], 
    Text([isManufactured]) AS [is_manufactured], 
    Text([isSaleable]) AS [is_saleable], 
    Text([color]) AS [color], 
    Text([safetyStockLevel]) AS [safety_stock_level], 
    Text([reorderPoint]) AS [reorder_point], 
    Text([standardCost]) AS [standard_cost], 
    Text([listPrice]) AS [list_price], 
    Text([size]) AS [size], 
    Text([sizeUnit]) AS [size_unit], 
    Text([weightUnit]) AS [weight_unit], 
    Text([weight]) AS [weight], 
    Text([daysToManufacture]) AS [days_to_manufacture], 
    Text([productLine]) AS [product_line], 
    Text([class]) AS [class], 
    Text([style]) AS [style], 
    Text([subcategory]) AS [subcategory], 
    Text([category]) AS [category], 
    Text([model]) AS [model], 
    Text([sellStartDate]) AS [sell_start_date], 
    Text([sellEndDate]) AS [sell_end_date], 
    Text([discontinuedDate]) AS [discontinued_date], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productId,
    name,
    productNumber,
    isManufactured,
    isSaleable,
    color,
    safetyStockLevel,
    reorderPoint,
    standardCost,
    listPrice,
    size,
    sizeUnit,
    weightUnit,
    weight,
    daysToManufacture,
    productLine,
    class,
    style,
    subcategory,
    category,
    model,
    sellStartDate,
    sellEndDate,
    discontinuedDate,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='SpecialOffers',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__special_offers = '$(val__qvd_path__das)/raw__adventure_works__special_offers.qvd';
TRACE Stored [raw__adventure_works__special_offers] into [$(val__qvd_path__special_offers)];
STORE [raw__adventure_works__special_offers] INTO [$(val__qvd_path__special_offers)] (qvd);
DROP TABLE [raw__adventure_works__special_offers];


Trace
-------------------------------------------------------------------
    Extracting State Provinces
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__state_provinces]:
LOAD
    Text([addressId]) AS [address_id], 
    Text([addressLine1]) AS [address_line1], 
    Text([addressLine2]) AS [address_line2], 
    Text([city]) AS [city], 
    Text([state]) AS [state], 
    Text([country]) AS [country], 
    Text([postalCode]) AS [postal_code], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    addressId,
    addressLine1,
    addressLine2,
    city,
    state,
    country,
    postalCode,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='StateProvinces',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__state_provinces = '$(val__qvd_path__das)/raw__adventure_works__state_provinces.qvd';
TRACE Stored [raw__adventure_works__state_provinces] into [$(val__qvd_path__state_provinces)];
STORE [raw__adventure_works__state_provinces] INTO [$(val__qvd_path__state_provinces)] (qvd);
DROP TABLE [raw__adventure_works__state_provinces];


Trace
-------------------------------------------------------------------
    Extracting Stores
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__stores]:
LOAD
    Text([businessEntityID]) AS [business_entity_id], 
    Text([addresses]) AS [addresses], 
    Text([contacts]) AS [contacts]
;

SELECT
    businessEntityID,
    addresses,
    contacts

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Stores',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__stores = '$(val__qvd_path__das)/raw__adventure_works__stores.qvd';
TRACE Stored [raw__adventure_works__stores] into [$(val__qvd_path__stores)];
STORE [raw__adventure_works__stores] INTO [$(val__qvd_path__stores)] (qvd);
DROP TABLE [raw__adventure_works__stores];


Trace
-------------------------------------------------------------------
    Extracting Transaction Histories
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__transaction_histories]:
LOAD
    Text([productId]) AS [product_id], 
    Text([name]) AS [name], 
    Text([productNumber]) AS [product_number], 
    Text([isManufactured]) AS [is_manufactured], 
    Text([isSaleable]) AS [is_saleable], 
    Text([color]) AS [color], 
    Text([safetyStockLevel]) AS [safety_stock_level], 
    Text([reorderPoint]) AS [reorder_point], 
    Text([standardCost]) AS [standard_cost], 
    Text([listPrice]) AS [list_price], 
    Text([size]) AS [size], 
    Text([sizeUnit]) AS [size_unit], 
    Text([weightUnit]) AS [weight_unit], 
    Text([weight]) AS [weight], 
    Text([daysToManufacture]) AS [days_to_manufacture], 
    Text([productLine]) AS [product_line], 
    Text([class]) AS [class], 
    Text([style]) AS [style], 
    Text([subcategory]) AS [subcategory], 
    Text([category]) AS [category], 
    Text([model]) AS [model], 
    Text([sellStartDate]) AS [sell_start_date], 
    Text([sellEndDate]) AS [sell_end_date], 
    Text([discontinuedDate]) AS [discontinued_date], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productId,
    name,
    productNumber,
    isManufactured,
    isSaleable,
    color,
    safetyStockLevel,
    reorderPoint,
    standardCost,
    listPrice,
    size,
    sizeUnit,
    weightUnit,
    weight,
    daysToManufacture,
    productLine,
    class,
    style,
    subcategory,
    category,
    model,
    sellStartDate,
    sellEndDate,
    discontinuedDate,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='TransactionHistories',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__transaction_histories = '$(val__qvd_path__das)/raw__adventure_works__transaction_histories.qvd';
TRACE Stored [raw__adventure_works__transaction_histories] into [$(val__qvd_path__transaction_histories)];
STORE [raw__adventure_works__transaction_histories] INTO [$(val__qvd_path__transaction_histories)] (qvd);
DROP TABLE [raw__adventure_works__transaction_histories];


Trace
-------------------------------------------------------------------
    Extracting Transaction History Archives
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__transaction_history_archives]:
LOAD
    Text([transactionId]) AS [transaction_id], 
    Text([productId]) AS [product_id], 
    Text([referenceOrderId]) AS [reference_order_id], 
    Text([referenceOrderLineId]) AS [reference_order_line_id], 
    Text([transactionDate]) AS [transaction_date], 
    Text([transactionType]) AS [transaction_type], 
    Text([quantity]) AS [quantity], 
    Text([actualCost]) AS [actual_cost], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    transactionId,
    productId,
    referenceOrderId,
    referenceOrderLineId,
    transactionDate,
    transactionType,
    quantity,
    actualCost,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='TransactionHistoryArchives',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__transaction_history_archives = '$(val__qvd_path__das)/raw__adventure_works__transaction_history_archives.qvd';
TRACE Stored [raw__adventure_works__transaction_history_archives] into [$(val__qvd_path__transaction_history_archives)];
STORE [raw__adventure_works__transaction_history_archives] INTO [$(val__qvd_path__transaction_history_archives)] (qvd);
DROP TABLE [raw__adventure_works__transaction_history_archives];


Trace
-------------------------------------------------------------------
    Extracting Unit Measures
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__unit_measures]:
LOAD
    Text([billOfMaterialsId]) AS [bill_of_materials_id], 
    Text([productAssemblyId]) AS [product_assembly_id], 
    Text([componentId]) AS [component_id], 
    Text([startDate]) AS [start_date], 
    Text([endDate]) AS [end_date], 
    Text([measurementUnit]) AS [measurement_unit], 
    Text([bomlevel]) AS [bomlevel], 
    Text([perAssemblyQuantity]) AS [per_assembly_quantity], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    billOfMaterialsId,
    productAssemblyId,
    componentId,
    startDate,
    endDate,
    measurementUnit,
    bomlevel,
    perAssemblyQuantity,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='UnitMeasures',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__unit_measures = '$(val__qvd_path__das)/raw__adventure_works__unit_measures.qvd';
TRACE Stored [raw__adventure_works__unit_measures] into [$(val__qvd_path__unit_measures)];
STORE [raw__adventure_works__unit_measures] INTO [$(val__qvd_path__unit_measures)] (qvd);
DROP TABLE [raw__adventure_works__unit_measures];


Trace
-------------------------------------------------------------------
    Extracting Vendors
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__vendors]:
LOAD
    Text([vendorId]) AS [vendor_id], 
    Text([accountNumber]) AS [account_number], 
    Text([name]) AS [name], 
    Text([creditRating]) AS [credit_rating], 
    Text([isPreferred]) AS [is_preferred], 
    Text([isActive]) AS [is_active], 
    Text([purchasingWebServiceUrl]) AS [purchasing_web_service_url], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    vendorId,
    accountNumber,
    name,
    creditRating,
    isPreferred,
    isActive,
    purchasingWebServiceUrl,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='Vendors',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__vendors = '$(val__qvd_path__das)/raw__adventure_works__vendors.qvd';
TRACE Stored [raw__adventure_works__vendors] into [$(val__qvd_path__vendors)];
STORE [raw__adventure_works__vendors] INTO [$(val__qvd_path__vendors)] (qvd);
DROP TABLE [raw__adventure_works__vendors];


Trace
-------------------------------------------------------------------
    Extracting Work Order Routings
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__work_order_routings]:
LOAD
    Text([locationId]) AS [location_id], 
    Text([name]) AS [name], 
    Text([costRate]) AS [cost_rate], 
    Text([availability]) AS [availability], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    locationId,
    name,
    costRate,
    availability,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='WorkOrderRoutings',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__work_order_routings = '$(val__qvd_path__das)/raw__adventure_works__work_order_routings.qvd';
TRACE Stored [raw__adventure_works__work_order_routings] into [$(val__qvd_path__work_order_routings)];
STORE [raw__adventure_works__work_order_routings] INTO [$(val__qvd_path__work_order_routings)] (qvd);
DROP TABLE [raw__adventure_works__work_order_routings];


Trace
-------------------------------------------------------------------
    Extracting Work Orders
-------------------------------------------------------------------
;
LIB CONNECT TO 'adventure_works__odata';

[raw__adventure_works__work_orders]:
LOAD
    Text([productId]) AS [product_id], 
    Text([name]) AS [name], 
    Text([productNumber]) AS [product_number], 
    Text([isManufactured]) AS [is_manufactured], 
    Text([isSaleable]) AS [is_saleable], 
    Text([color]) AS [color], 
    Text([safetyStockLevel]) AS [safety_stock_level], 
    Text([reorderPoint]) AS [reorder_point], 
    Text([standardCost]) AS [standard_cost], 
    Text([listPrice]) AS [list_price], 
    Text([size]) AS [size], 
    Text([sizeUnit]) AS [size_unit], 
    Text([weightUnit]) AS [weight_unit], 
    Text([weight]) AS [weight], 
    Text([daysToManufacture]) AS [days_to_manufacture], 
    Text([productLine]) AS [product_line], 
    Text([class]) AS [class], 
    Text([style]) AS [style], 
    Text([subcategory]) AS [subcategory], 
    Text([category]) AS [category], 
    Text([model]) AS [model], 
    Text([sellStartDate]) AS [sell_start_date], 
    Text([sellEndDate]) AS [sell_end_date], 
    Text([discontinuedDate]) AS [discontinued_date], 
    Text([modifiedDate]) AS [modified_date]
;

SELECT
    productId,
    name,
    productNumber,
    isManufactured,
    isSaleable,
    color,
    safetyStockLevel,
    reorderPoint,
    standardCost,
    listPrice,
    size,
    sizeUnit,
    weightUnit,
    weight,
    daysToManufacture,
    productLine,
    class,
    style,
    subcategory,
    category,
    model,
    sellStartDate,
    sellEndDate,
    discontinuedDate,
    modifiedDate

FROM
    JsonV4GetData

WITH PROPERTIES (
    oDataResourcePath='WorkOrders',
    oDataQueryOptions='',
    maxDepth='',
    maxResults=''
);

LET val__qvd_path__work_orders = '$(val__qvd_path__das)/raw__adventure_works__work_orders.qvd';
TRACE Stored [raw__adventure_works__work_orders] into [$(val__qvd_path__work_orders)];
STORE [raw__adventure_works__work_orders] INTO [$(val__qvd_path__work_orders)] (qvd);
DROP TABLE [raw__adventure_works__work_orders];

